#Updated by SystemSettingsPanel
#Sun Oct 26 15:15:18 CST 2025
database.username=root
rent.mindays=1
database.url=jdbc\:mysql\://10.245.203.137\:3306/car_rental_system?useSSL\=false&serverTimezone\=UTC&characterEncoding\=utf8
database.password=12345678
database.driver=com.mysql.cj.jdbc.Driver
fine.dailyrate=50.00
system.version=1.0
ui.font=\u00E5\u00BE\u00AE\u00E8\u00BD\u00AF\u00E9\u009B\u0085\u00E9\u00BB\u0091
ui.fontsize=12
system.name=CarRentalSystem
ui.lookandfeel=system
rent.maxdays=31
system.author=IIawaII
